spring:
  profiles:
    active: prod

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/cash-control
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    database: mysql


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true

springdoc:
   swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework: INFO
    com:
      everton: DEBUG

